name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt update && sudo apt install g++ -y

    - name: Build
      run: g++ -std=c++11 main.cpp src/utils.cpp -o program

    - name: Run
      run: ./program < input.txt || true

