name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted  # Ensure this is a Windows self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for g++
        shell: powershell
        run: |
          if (-not (Get-Command g++ -ErrorAction SilentlyContinue)) {
            Write-Error "g++ not found. Please install MinGW or another C++ compiler manually on this Windows runner."
            exit 1
          } else {
            Write-Output "g++ is installed."
          }

      - name: Compile C++ code
        shell: powershell
        run: |
          g++ -std=c++11 main.cpp src\\utils.cpp -o program.exe
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Compilation failed."
            exit 1
          }

      - name: Run the program
        shell: powershell
        run: |
          if (Test-Path "input.txt") {
            Get-Content input.txt | .\program.exe
          } else {
            Write-Output "input.txt not found. Running without input redirection."
            .\program.exe
          }
